kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: geekbeacon/gb-ghost
      tags: 4.3.2
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
