kind: pipeline
name: default

steps:
  - name: test
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - ln -s env.template .env
      - docker-compose -f production.yml build
      - echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - docker-compose push


volumes:
    - name: docker_socket
      host:
        path: /var/run/docker.sock