version: "3.7"
services:
  ghost:
    image: geekbeacon/gb-ghost:4.47.0
    build:
      context: .
    volumes:
      - ./keys:/var/lib/ghost/keys/
    ports:
      - 8080:2368
    env_file: .env
  mail:
    image: mailhog/mailhog:v1.0.1
    container_name: mail
    ports:
      - 8025:8025
