version: 2.1
jobs:
 build:
   working_directory: /app
   docker:
     - image: docker:20.10.3
   steps:
     - checkout
     - setup_remote_docker:
         docker_layer_caching: false
     - run:
         name: Setup env
         command: ln -s env.template .env
     - run: 
         name: loginto docker
         command: |
           echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: 
         name: Install Docker Compose 
         command: | 
            set -x curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose &&  chmod +x /usr/local/bin/docker-compose
     - run: 
        name: Setup docker-compose alias
        command: ln -s production.yml docker-compose.yml
     - run: 
        name: build docker
        command: docker-compose build        
     - run:
         name: Docker Push
         command: docker-compose push ghost

workflows:
  publish_image: 
    jobs:
      - build: 
          context:
            - DOCKER
          filters:
            branches:
              only: master          

